name: sensor_env
channels:
  - apple
  - conda-forge
dependencies:
  - aom=3.4.0=hbe31e94_1
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb18efdd_2
  - asttokens=2.0.8=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bleach=5.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2022.9.24=h4653dfc_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h73a0509_1014
  - cffi=1.15.1=py39h04d3946_0
  - debugpy=1.6.3=py39h3c22d25_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.1.0=pyhd8ed1ab_0
  - expat=2.4.9=hb7217d7_0
  - ffmpeg=4.4.2=gpl_hfdc7bce_107
  - flit-core=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h82840c6_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hd633e50_0
  - gettext=0.19.8.1=h0186832_1009
  - gmp=6.2.1=h9f76cd9_0
  - gnutls=3.7.7=h27a1928_0
  - graphite2=1.3.13=h9f76cd9_1001
  - grpcio=1.46.3=py39h365d37b_0
  - h5py=3.6.0=nompi_py39hd982b79_100
  - harfbuzz=4.4.1=hd36a07e_0
  - hdf5=1.12.1=nompi_hd9dbc9e_104
  - icu=70.1=h6b3803e_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - ipykernel=6.16.0=pyh736e0ef_0
  - ipython=8.5.0=pyhd1c38e8_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.2=pyhd8ed1ab_1
  - jasper=2.0.33=hba35424_0
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=he4db4b2_2
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py39h2804cbe_7
  - jupyter_client=7.3.5=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py39h2804cbe_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.3=pyhd8ed1ab_0
  - krb5=1.19.3=he492e65_0
  - lame=3.100=h27ca646_1001
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.83.1=h7965298_0
  - libcxx=14.0.6=h2692d47_0
  - libdeflate=1.14=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=11_3_0_hd922786_25
  - libgfortran5=11.3.0=hdaf2cc0_25
  - libglib=2.72.1=ha1047ec_0
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.3=he4db4b2_0
  - liblapack=3.9.0=16_osxarm64_openblas
  - liblapacke=3.9.0=16_osxarm64_openblas
  - libnghttp2=1.47.0=h519802c_1
  - libopenblas=0.3.21=openmp_hc731615_3
  - libopencv=4.5.5=py39h982fb10_7
  - libpng=1.6.38=h76d750c_0
  - libprotobuf=3.19.4=hccf11d3_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.39.3=h76d750c_0
  - libssh2=1.10.0=h7a5bd25_3
  - libtasn1=4.19.0=h1a8c8d9_0
  - libtiff=4.4.0=hfa0b094_4
  - libunistring=0.9.10=h3422bc3_0
  - libvpx=1.11.0=hc470f4d_3
  - libwebp-base=1.2.4=h57fd34a_0
  - libxml2=2.10.2=ha9542bf_1
  - libzlib=1.2.12=h03a7124_3
  - llvm-openmp=14.0.4=hd125106_0
  - markupsafe=2.1.1=py39hb18efdd_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=0.8.4=py39h5161555_1005
  - nbclient=0.5.13=pyhd8ed1ab_0
  - nbconvert=6.4.5=py39h2804cbe_0
  - nbformat=5.6.1=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - nettle=3.8.1=h63371fa_1
  - notebook=6.4.12=pyha770c72_0
  - numpy=1.23.2=py39h3668e8b_0
  - opencv=4.5.5=py39hdf13c20_7
  - openh264=2.3.0=h9a09cb3_0
  - openssl=3.0.5=h03a7124_2
  - p11-kit=0.24.1=h29577a5_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=hbdafb3b_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=22.2.2=pyhd8ed1ab_0
  - pixman=0.40.0=h27ca646_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.31=pyha770c72_0
  - prompt_toolkit=3.0.31=hd8ed1ab_0
  - protobuf=3.19.4=py39hfb83b0d_0
  - psutil=5.9.2=py39h02fc5c5_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-opencv=4.5.5=py39hfa6204d_7
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py39hb18efdd_1
  - python=3.9.13=h96fcbfb_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pyzmq=24.0.1=py39h0553236_0
  - readline=8.1.2=h46ed386_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.4.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.39.3=h2229b38_0
  - stack_data=0.5.1=pyhd8ed1ab_0
  - svt-av1=1.2.1=he23bcac_0
  - tensorflow-deps=2.10.0=0
  - terminado=0.15.0=py39h2804cbe_0
  - testpath=0.6.0=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - tornado=6.2=py39h9eb174b_0
  - traitlets=5.4.0=pyhd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzdata=2022d=h191b570_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.3=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xz=5.2.6=h57fd34a_0
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h03a7124_3
  - zstd=1.5.2=h8128057_4
  - pip:
    - absl-py==1.2.0
    - astunparse==1.6.3
    - cachetools==5.2.0
    - certifi==2022.9.24
    - charset-normalizer==2.1.1
    - flatbuffers==2.0.7
    - gast==0.4.0
    - google-auth==2.11.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - idna==3.4
    - importlib-metadata==4.12.0
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.6
    - markdown==3.4.1
    - oauthlib==3.2.1
    - open3d==0.15.1
    - opt-einsum==3.3.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.10.0
    - tensorflow-macos==2.10.0
    - tensorflow-metal==0.6.0
    - termcolor==2.0.1
    - urllib3==1.26.12
    - werkzeug==2.2.2
    - wrapt==1.14.1
